import type { Audience, Depth, GuideLanguage } from '@/lib/guides/catalogue';
import shots from '@/lib/guides/shots.json';
import type { WalkStep } from '@/components/walkthrough';
import { STEP_TEXT } from '@/lib/guides/step-text';

/**
 * The walkthroughs, assembled from two halves that are kept apart on purpose.
 *
 * - `step-text.json` holds the words, written by hand in Hebrew and English
 *   from the Center's own guides in Drive, with a one-sentence `quick` version
 *   on the steps the quick walkthrough keeps.
 * - `shots.json` is generated by `scripts/guides/capture.mjs`: the size of each
 *   screenshot and the measured box of every control to ring on it.
 *
 * A step with words and no screenshot is left out rather than shown blank, so a
 * capture run that missed a screen shortens the guide instead of breaking it.
 */

type Shots = Record<string, Record<string, Partial<Record<GuideLanguage, { width: number; height: number; spots: WalkStep['spots'] }>>>>;

export function walkthrough(audience: Audience, language: GuideLanguage, depth: Depth = 'deep'): WalkStep[] {
  const measured = (shots as Shots)[audience] ?? {};
  return STEP_TEXT[audience].flatMap((step) => {
    const shot = measured[step.id]?.[language];
    if (!shot) return [];
    if (depth === 'quick' && !step.quick) return [];
    return [
      {
        id: step.id,
        title: step.title[language],
        body: depth === 'quick' && step.quick ? step.quick[language] : step.body[language],
        image: `/api/guides/steps/${audience}/${language}/${step.id}.png`,
        width: shot.width,
        height: shot.height,
        spots: shot.spots,
      },
    ];
  });
}
