/**
 * Builds what the phone scanner runs in: public/vendor/opencv.js and
 * public/vendor/scan-worker.js.
 *
 * ── why a worker ────────────────────────────────────────────────────────────
 *
 * OpenCV.js compiles WebAssembly and builds functions from strings (`new
 * Function`) as it starts. The site's Content-Security-Policy rightly forbids
 * the second in every page, and loosening it site-wide to let one feature run
 * would be the wrong trade. A Web Worker loaded from its own file is governed
 * by the policy that file is served with, and /vendor/ is served with none
 * (see the matcher in src/proxy.ts). So OpenCV runs in the worker, the page
 * sends it pixels and receives pixels, and the page itself stays under the
 * strict policy.
 *
 * ── one source for the image code ────────────────────────────────────────────
 *
 * The worker's pipeline is src/lib/scan/document.ts, transpiled here - the same
 * file the unit tests exercise - so there is no second copy to drift. Both files
 * are generated on every dev and build rather than committed.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const VENDOR = path.join(ROOT, 'public', 'vendor');
fs.mkdirSync(VENDOR, { recursive: true });

const cvFrom = path.join(ROOT, 'node_modules', '@techstark', 'opencv-js', 'dist', 'opencv.js');
fs.copyFileSync(cvFrom, path.join(VENDOR, 'opencv.js'));

const source = fs.readFileSync(path.join(ROOT, 'src', 'lib', 'scan', 'document.ts'), 'utf8');
const { outputText } = ts.transpileModule(source, {
  compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020 },
});

const worker = `/* Generated by scripts/copy-opencv.mjs from src/lib/scan/document.ts. Do not edit. */
importScripts('/vendor/opencv.js');
var exports = {};
var module = { exports: exports };
${outputText}
var scan = exports;

var ready = new Promise(function (resolve) {
  var m = self.cv;
  if (m && typeof m.then === 'function') {
    m.then(function (cv) { delete cv.then; self.cv = cv; resolve(cv); });
  } else if (m && m.Mat) {
    resolve(m);
  } else {
    m.onRuntimeInitialized = function () { resolve(m); };
  }
});

function toImageData(cv, mat) {
  var rgba = mat;
  if (mat.channels() !== 4) {
    rgba = new cv.Mat();
    cv.cvtColor(mat, rgba, mat.channels() === 1 ? cv.COLOR_GRAY2RGBA : cv.COLOR_RGB2RGBA);
  }
  var out = new ImageData(new Uint8ClampedArray(rgba.data), rgba.cols, rgba.rows);
  if (rgba !== mat) rgba.delete();
  return out;
}

self.onmessage = function (event) {
  var msg = event.data;
  ready.then(function (cv) {
    try {
      if (msg.op === 'ping') return self.postMessage({ id: msg.id, ok: true });
      var src = cv.matFromImageData(msg.image);
      if (msg.op === 'detect') {
        var quad = scan.findPage(cv, src);
        src.delete();
        return self.postMessage({ id: msg.id, ok: true, quad: quad });
      }
      if (msg.op === 'render') {
        var flat = scan.flatten(cv, src, msg.quad);
        var done = scan.finish(cv, flat, msg.look);
        var turned = done;
        for (var i = 0; i < (msg.turns % 4); i++) {
          var next = new cv.Mat();
          cv.rotate(turned, next, cv.ROTATE_90_CLOCKWISE);
          if (turned !== done) turned.delete();
          turned = next;
        }
        var image = toImageData(cv, turned);
        src.delete(); flat.delete(); done.delete();
        if (turned !== done) turned.delete();
        return self.postMessage({ id: msg.id, ok: true, image: image }, [image.data.buffer]);
      }
      src.delete();
      self.postMessage({ id: msg.id, ok: false, error: 'unknown op' });
    } catch (e) {
      self.postMessage({ id: msg.id, ok: false, error: String(e) });
    }
  });
};
`;
fs.writeFileSync(path.join(VENDOR, 'scan-worker.js'), worker);
console.log('vendor: opencv.js, scan-worker.js');
